module.exports = {
    GET_CONNECTED: "GET_CONNECTED",
    USER_CONNECTED: "USER_CONNECTED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    VERIFY_USER: "VERIFY_USER",
    PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
    CONNECTION_CREATED: "CONNECTION_CREATED"
}