module.exports = {
    USER_CONNECTED: "USER_CONNECTED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    VERIFY_USER: "VERIFY_USER",
    PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
    CONNECTION_CREATED: "CONNECTION_CREATED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    USER_LEFT: "USER_LEFT",
    OTHER_PLAYER_LEFT: "OTHER_PLAYER_LEFT"
}